apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: prometheus-operator-admission
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-admission
webhooks:
  - clientConfig:
      service:
        name: prometheus-operator-operator
        namespace: prometheus
        path: /admission-prometheusrules/mutate
    failurePolicy: Ignore
    name: prometheusrulemutate.monitoring.coreos.com
    rules:
      - apiGroups:
          - monitoring.coreos.com
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - prometheusrules
