apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app: prometheus-operator-alertmanager
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-alertmanager
  namespace: prometheus
spec:
  baseImage: quay.io/prometheus/alertmanager
  externalUrl: http://prometheus-operator-alertmanager.prometheus:9093
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: web
  replicas: 1
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-operator-alertmanager
  version: v0.20.0
