apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-alertmanager
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-alertmanager
  namespace: prometheus
spec:
  endpoints:
    - path: /metrics
      port: web
  namespaceSelector:
    matchNames:
      - prometheus
  selector:
    matchLabels:
      app: prometheus-operator-alertmanager
      release: prometheus-operator
      self-monitor: 'true'
