apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-1.10.0
    heritage: Tiller
    jobLabel: node-exporter
    release: prometheus-operator
  name: psp-prometheus-operator-prometheus-node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-prometheus-operator-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-operator-prometheus-node-exporter
    namespace: prometheus
