apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-operator-operator
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-operator
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-operator-operator
      release: prometheus-operator
  template:
    metadata:
      labels:
        app: prometheus-operator-operator
        chart: prometheus-operator-8.14.0
        heritage: Tiller
        release: prometheus-operator
    spec:
      containers:
        - args:
            - --manage-crds=true
            - --kubelet-service=kube-system/prometheus-operator-kubelet
            - --logtostderr=true
            - --localhost=127.0.0.1
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.38.1
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
            - --config-reloader-cpu=100m
            - --config-reloader-memory=25Mi
          image: quay.io/coreos/prometheus-operator:v0.38.1
          imagePullPolicy: IfNotPresent
          name: prometheus-operator
          ports:
            - containerPort: 8080
              name: http
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
        - args:
            - server
            - --listen=:8443
            - --target=127.0.0.1:8080
            - --key=cert/key
            - --cert=cert/cert
            - --disable-authentication
          image: squareup/ghostunnel:v1.5.2
          imagePullPolicy: IfNotPresent
          name: tls-proxy
          ports:
            - containerPort: 8443
              name: https
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /cert
              name: tls-proxy-secret
              readOnly: true
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator-operator
      volumes:
        - name: tls-proxy-secret
          secret:
            defaultMode: 420
            secretName: prometheus-operator-admission
