apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-operator
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-operator
  namespace: prometheus
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: prometheus-operator-operator
    release: prometheus-operator
  type: ClusterIP
