apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-kube-etcd
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    jobLabel: kube-etcd
    release: prometheus-operator
  name: prometheus-operator-kube-etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    component: etcd
  type: ClusterIP
