apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-kube-controller-manager
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    jobLabel: kube-controller-manager
    release: prometheus-operator
  name: prometheus-operator-kube-controller-manager
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10252
      protocol: TCP
      targetPort: 10252
  selector:
    component: kube-controller-manager
  type: ClusterIP
