apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-kube-proxy
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    jobLabel: kube-proxy
    release: prometheus-operator
  name: prometheus-operator-kube-proxy
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  type: ClusterIP
