apiVersion: v1
data:
  datasource.yaml: "apiVersion: 1\ndatasources:\n- name: Prometheus\n  type: prometheus\n\
    \  url: http://prometheus-operator-prometheus:9090/\n  access: proxy\n  isDefault:\
    \ true"
kind: ConfigMap
metadata:
  labels:
    app: prometheus-operator-grafana
    chart: prometheus-operator-8.14.0
    grafana_datasource: '1'
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-grafana-datasource
  namespace: prometheus
