apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-grafana
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-grafana
  namespace: prometheus
spec:
  endpoints:
    - path: /metrics
      port: service
  namespaceSelector:
    matchNames:
      - prometheus
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-operator
      app.kubernetes.io/name: grafana
