apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-2.8.8
  name: psp-prometheus-operator-kube-state-metrics
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - prometheus-operator-kube-state-metrics
    resources:
      - podsecuritypolicies
    verbs:
      - use
