apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission
    chart: prometheus-operator-8.14.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-admission
  namespace: prometheus
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create
